[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_tickets_anchor = "7fM8upzdwQoXLDprTj1B32JqbRHNH3aVts9q2y8Dyp36"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
